ladybug-tools/dragonfly-core

README.md

The URL mentioned in README.md gives me a fatal result. Corrected the URL provided.

Updated the URL for cloning the repo

---

.releaserc.json
.travis.yml
deploy.sh
dragonfly/building.py
dragonfly/room2d.py
dragonfly/story.py
requirements.txt
tests/building_test.py
tests/room2d_test.py
tests/story_test.py

You were right @mostapharoudsari that the multiplier is better implemented on the Story object rather than having it as a list on the Building.
I also made use of the recent Polygon2D intersection functionality to add methods that intersect adjacent Room2Ds with one another.

fix(multiplier): Move multiplier property to Story object

---

README.md
dragonfly/building.py
dragonfly/room2d.py
dragonfly/subdivide.py
tests/building_test.py
tests/room2d_test.py
tests/subdivide_test.py

This commit adds a couple of classmethods that will be used to create Building objects from Grasshopper. The first creates a full building from_footprint and an array of floor_to_floor heights. The second creates a building from an array of all floor geometries and automatically determines which geometries are unique.
This commit also adds a couple of utilities to interpret instructions for subdividing building massing, which follow the convention laid out in honeybee-legacy.

feat(building): Add classmethods from footprint and all_story_geometry

---

dragonfly/building.py
dragonfly/room2d.py
dragonfly/shadingparameter.py
dragonfly/story.py
dragonfly/subdivide.py
tests/building_test.py
tests/shadingparameter_test.py
tests/subdivide_test.py

I originally had these methods within Grasshopper components but realized that they really should be here in the core.

feat(building): Add methods for honeybee Models from Building arrays

---

dragonfly/_base.py
dragonfly/building.py
dragonfly/context.py
dragonfly/extensionutil.py
dragonfly/model.py
dragonfly/properties.py
dragonfly/room2d.py
dragonfly/story.py
tests/building_test.py
tests/context_test.py
tests/model_test.py
tests/room2d_test.py
tests/story_test.py

@mostaphaRoudsari ,  this is the code that is needed to generate the samples for Konrad (since a Dragonfly Model JSON is ultimately what we want to be getting out of Revit).
I still have to add some tests and this PR has to be coordinated with another one over on dragonfly-energy but the code here should not change and is ready for your review.

feat(model): Add objects for Dragonfly Model and ContextShade

---

dragonfly/building.py
dragonfly/context.py
dragonfly/properties.py
dragonfly/room2d.py
dragonfly/story.py
tests/building_test.py

These methods were originally hidden but, after remembering how I had implemented similar methods in honeybee, I decided to make them public and more robust for different use cases.

feat(add_prefix): Add add_prefix method to help with renaming

---

dragonfly/building.py
dragonfly/room2d.py
dragonfly/shadingparameter.py
dragonfly/story.py
dragonfly/windowparameter.py
tests/building_test.py
tests/room2d_test.py
tests/story_test.py

We were originally storing the ground and exterior roof boundary conditions on the Story class but, over the last couple of months, I realized that this created more inflexibility than it did convenience.  There are just too many common cases where you have two rooms in the same story but one has an exterior roof above it while the other has another floor. So these properties are now stored on the Room2D-level.

feat(room2d): Move is_ground_contact and is_top_exposed to Room2D

---

dragonfly/room2d.py
dragonfly/shadingparameter.py
dragonfly/windowparameter.py
tests/room2d_test.py
tests/shadingparameter_test.py
tests/windowparameter_test.py

This commit fixes [this bug here](https://github.com/ladybug-tools/dragonfly-core/issues/22).

fix(facade_parameter): Get facade parameters to respond to scaling

---

dragonfly/windowparameter.py

I realized that I would rather not use the Polygon2D schema if I can avoid it. I think lists of point lists will be cleaner.

feat(windowparameter): Tweak to schema for detailed windows

---

dragonfly/room2d.py
dragonfly/windowparameter.py
tests/windowparameter_test.py

Mostapha made me realize that the word 'Detailed' wasn't helping us too much in the class name.

feat(windowparameter): Shortened class name to RectangularWindows

---

.gitignore
README.md
dev-requirements.txt
docs/cli.rst
docs/conf.py
docs/index.rst
dragonfly/__main__.py
dragonfly/cli/__init__.py
dragonfly/cli/validate.py
setup.py
tests/cli_test.py

Adding a CLI that can validate Dragonfly schema JSONs and can be extended by estensions.

feat(cli): Add CLI and add validation commands

---

dragonfly/windowparameter.py
requirements.txt
tests/windowparameter_test.py

This commit addressed this issue:
https://github.com/ladybug-tools/dragonfly-core/issues/33

feat(windowparameter): Add RepeatingWindowWidthHeight

---

dragonfly/model.py

I realized that there are several cases where it will be helpful to get the Python dictionary of the geoJSON separate from just the geoJSON file (in case we want to edit the JSON before we write it).

feat(model): Deconstruct to_geojson into to_geojson_dict and to_geojson

---

dragonfly/building.py
dragonfly/cli/edit.py
dragonfly/cli/validate.py
dragonfly/model.py
dragonfly/projection.py
dragonfly/room2d.py
dragonfly/story.py
dragonfly/subdivide.py
dragonfly/windowparameter.py

This commit also fixes a lot of typos

fix(cli): Use correct type for list input

---

dragonfly/building.py
dragonfly/context.py
dragonfly/model.py
dragonfly/properties.py
dragonfly/room2d.py
dragonfly/story.py

This is something that has been implemented in honeybee-core and we will eventually need for dragonfly-core as well.
This PR also serves as a test for the new dependabot system.

feat(transform): Add methods to transform extension properties

---

dragonfly/cli/edit.py

Resolves https://github.com/ladybug-tools/dragonfly-core/issues/102

fix(cli): Change --log-file to --output-file in CLI commands

---

dragonfly/room2d.py
requirements.txt
tests/story_test.py

Resolves https://github.com/ladybug-tools/dragonfly-core/issues/87

fix(story): Transfer story property to honeybee

---

dragonfly/building.py
dragonfly/model.py
dragonfly/room2d.py
dragonfly/story.py
tests/building_test.py
tests/model_test.py
tests/room2d_test.py
tests/story_test.py

This commit adds a method to the story object that enables one to easily turn a story into a basement.
It also adds several properties that make it easy to track the number of stories above ground.

feat(basement): Add properties and methods for adding basements

---

dragonfly/_base.py
dragonfly/building.py
dragonfly/cli/__init__.py
dragonfly/cli/edit.py
dragonfly/cli/validate.py
dragonfly/model.py
dragonfly/projection.py
dragonfly/room2d.py
dragonfly/story.py
dragonfly/windowparameter.py
tests/geojson/TestGeoJSON.geojson

This brings the style of the repo up to flake8 standars. In the process of updating the style, I also fixed a couple of real bugs that results from typos.

fix(typos): Fix a few typos and update style to flake8

---

dragonfly/building.py
requirements.txt

This fixes a compatibility issue with the new ladybug-geometry-polyskel and also means that holes in building footprints are now supported.

fix(deps): bump ladybug-geometry-polyskel l from 1.1.0 to 1.2.0

---

dragonfly/building.py

The few cases I found where it works produce odd results.

fix(polyskel): Remove use of holes for now

---

dragonfly/room2d.py

Resolves https://github.com/ladybug-tools/dragonfly-core/issues/152
Thanks for finding this one @saeranv .

fix(room2d): Fix bug in returned adjacency info

---

dragonfly/building.py
dragonfly/model.py
dragonfly/room2d.py
dragonfly/story.py
tests/model_test.py
tests/room2d_test.py
tests/story_test.py

I also fixed several bugs in the implementation of auto-generated plenums and exposed the auto-generated plenum option on the to_honeybee methods higher in the dragonfly schema hierarchy.

feat(story): Add floor_height property to Story

---

dragonfly/config.py
dragonfly/model.py

... and write this version into any dragonfly models.

feat(config): Add config module to sense dragonfly-schema version

---

dragonfly/dictutil.py

It's such a small bug that it's not worth a new release.

perf(dictutil): Ensure ContextShade is re-serialize-able

---

dragonfly/colorobj.py
dragonfly/room2d.py
tests/colorobj_test.py
tests/room2d_test.py

I'm also adding a module to help visualize the properties assigned to dragonfly models (so we don't always have to convert it to Honeybee).

feat(room2d): Add a means to set wall boundary conditions to adiabatic

---

dragonfly/building.py
dragonfly/model.py
dragonfly/story.py
tests/building_test.py
tests/model_test.py

I'm also adding the ability to cap the shade representations.
Resolves https://github.com/ladybug-tools/dragonfly-core/issues/21

feat(model): Add ability to export each story as a separate model

---

dragonfly/cli/__init__.py
dragonfly/cli/translate.py
tests/cli_test.py

It seems I forgot to add the command to main. I'm also changing the output to make it easier to loop over the HBJSONs in queenbee recipes.

fix(translate): Fix translation command to honeybee

---

dragonfly/cli/edit.py
dragonfly/cli/translate.py
dragonfly/cli/validate.py
dragonfly/model.py
dragonfly/properties.py
tests/model_test.py

I am also fixing some issues with the default tolerances applied in the from_geojson pathway. And I am adding methods for serializing to/from JSON and pkl.

fix(model): Add support for serializing more geoJSON attributes

---

docs/cli.rst
docs/cli/index.rst
docs/conf.py
docs/index.rst

Hi @chriswmackey,
Nice... second repo without issue on my side! Please take a look when you get a chance!

docs(cli): Improve CLI documentation structure

---

dragonfly/cli/translate.py
dragonfly/model.py

I am also updating the Model class to use the new honeybee.units module.

fix(cli): Allow users to specify the units of shade distance

---

dragonfly/model.py

This should generally help keep the file size smaller.

fix(model): Change default indent to None

---

dragonfly/cli/edit.py
dragonfly/cli/translate.py
dragonfly/model.py
tests/cli_test.py

The command includes a number of options to ease with importing, including options to assign windows by ratio and separate top and bottom floors.

feat(cli): Add a command to load models from geoJSON

---

dragonfly/building.py
dragonfly/story.py

This will be really helpful for cases of buildings with plinths where we only want to set the roofs of these plinths to be outdoor exposed.

fix(building): Add a method to separate mid stories

---

dragonfly/room2d.py

This option will allow for exterior windows, shades and boundary conditions to be transferred after the intersection calculation has been run.

fix(room2d): Add preserve_exterior option to intersect_adjacnecy

---

dragonfly/room2d.py

I'm also improving the method that removes colinear vertices.

fix(room2d): Add method to remove duplicate vertices

---

dragonfly/context.py

This was needed since certain geometries in Revit are meant to be attached to the building.

feat(context): Add a property for is_detached

---

dragonfly/story.py

This is a minor bug but was causing the Rhino plugin to fail to import the file after validation.

fix(story): room -> story

---

dragonfly/model.py

This commit also adds the CAD point information into the project property.

fix(model): Use model tolerance by default in GeoJSON serialization

---

dragonfly/building.py

This is not possible with the new offset methods that have been implemented in ladybug-geometry.

fix(building): Add support for perim offset in footprints with holes

---

dragonfly/building.py
dragonfly/model.py
dragonfly/story.py

Somehow we were failing to pass the units and tolerance.

fix(model): Fix bug in Model.duplicate()

---

dragonfly/cli/validate.py
dragonfly/model.py
dragonfly/story.py
tests/cli_test.py

This commit also adds automatic support for treating HBJSONs as dragonfly models upon serialization.

fix(validate): Add a check for Room2D overlaps

---

dragonfly/cli/validate.py
dragonfly/model.py
dragonfly/room2d.py
dragonfly/story.py

This commit is also changing the error codes so that there's better consistency among the geometric ValidationErrors.

fix(validate): Add two last validations for dragonfly Room2D

---

dragonfly/room2d.py

I'll have to dig deeper into why this failed but just letting the calculation proceed for now is fine.

fix(room2d): Catch the case of PolyBool failure

---

dragonfly/model.py
dragonfly/story.py

I'm also updating the messages in the validation errors to include the display_names of rooms.

fix(story): Resolve window conflicts when windows are way out there

---

dragonfly/building.py
dragonfly/cli/create.py
dragonfly/model.py

Now, all non-solid Rooms that cannot be translated to Room2D will just be left as invalid 3D rooms.

fix(building): Ensure non-solid 3D Rooms don't block Room2D Translation

---

dragonfly/room2d.py

This should give a cleaner result for some cases in the model editor where people are using fairly messy/complex polylines for alignment.

fix(room2d): Add pull_to_segments method that snaps only to closest seg

---

dragonfly/room2d.py

This new check will help catch the  case that vertical roof gaps happen between two edges that overlap in plan but share no end points.
This commit is also removing the translation of disconnected roof geometries to shade given that new improvements in the roof routine should mean that these disconnected geometries are always unwanted and should be removed.

fix(room2d): Perform an extra check to cap planar holes in roofs

---

dragonfly/model.py
dragonfly/room2d.py
dragonfly/story.py

I'm just realizing that I would want a method like this in order to handle all of the small Room2Ds produced by automatic core/perimeter zoning.

feat(story): Add a method to merge small Room2Ds together

---

dragonfly/room2d.py
dragonfly/story.py

This commit also includes an improvement to the join_small_room_2ds method, which gives an option of merging small rooms into the larger ones.

feat(room2d): Add methods for joining rooms into neighbor

---

dragonfly/context.py
dragonfly/room2d.py
tests/context_test.py

There is also a bug fix in the serializer of Dragonfly Room2D from Honeybee Room.

fix(context): Add methods to align and evaluate plane conformity

---

dragonfly/building.py
dragonfly/roof.py

Rooms with very complex domed roofs will now be left as 3D rooms in ExtrudedOnly. Also better criteria is used for merging coplanar roofs together.

style(roof): Use smarter criteria for when to import HB Room as Room2D

---

dragonfly/building.py
dragonfly/room2d.py
dragonfly/story.py

This can happen when you have rooms on a story that are double-height and they have a small plenum at the top.

fix(building): Handle plenums that differ too much to be adjacent
