ladybug-tools/dragonfly-core

- .travis.yml
- dragonfly/building.py
- dragonfly/properties.py
- dragonfly/room2d.py
- tests/building_test.py
This new code will ensure that ProgramTypes and ConstructionSets assigned to Dragonfly objects will be transferred to Honeybee objects.
Note that there isn't really a way to test this method within the dragonfly-core tests but the tests within the extensions will be using this code.
> feat(to_honeybee): Methods to transfer extension properties to_honeybee

- dragonfly/room2d.py
- dragonfly/windowparameter.py
- tests/room2d_test.py
- tests/windowparameter_test.py
This commit adds two new classes to the windowparameter module:
One that accepts window widths/heights along with an origin 2D point for each window within the plane of the wall. this one can be easily editable in schema form (just change width and height).  This includes checks to not generate windows if they are outside the boundary of the wall, meaning that someone can create a pattern of rectangular windows and then apply it to as many walls as they want.
One that accepts a list of 2D vertices within the plane of the wall. This one doesn't have the same checks but it allows for detailed specification of window faces.
> feat(windowparameter): Add classes to specify detailed windows

- docs/_static/custom.css
- docs/_templates/layout.html
- docs/conf.py
- dragonfly/_base.py
- dragonfly/building.py
- dragonfly/context.py
- dragonfly/extensionutil.py
- dragonfly/model.py
- dragonfly/properties.py
- dragonfly/room2d.py
- dragonfly/shadingparameter.py
- dragonfly/story.py
- dragonfly/subdivide.py
- dragonfly/windowparameter.py
Hi @chriswmackey,
I started with this library and I stumbled upon a couple of issues when generating the pages that I hope you can help me with:
1)  
Extension error:
Could not import extension sphinx_click.ext (exception: No module named click)
From the conf.py file I noticed the need of the sphinx-click extension so I installed it through pip:  pip install sphinx-click. 
At that point the message still comes up on the sphinx build command. I'm sure I'm missing a library or something. Any suggestions?
2)
When I disabled the sphinx-click extension to generate the pages that don't need it found this error:
Traceback (most recent call last):
File "c:\python27\lib\site-packages\sphinx\ext\autodoc\importer.py", line 154, in import_module
__import__(modname)
File …
> Format docstrings for correct display in sphinx-generated bootstrap pages

- dragonfly/cli/__init__.py
- dragonfly/cli/edit.py
- dragonfly/cli/validate.py
- dragonfly/model.py
- dragonfly/room2d.py
- dragonfly/story.py
- tests/cli_test.py
- tests/json/sample_revit_model.json
- tests/model_test.py
- tests/room2d_test.py
This commit adds a command that solves adjacency across a Model by removing colinera vertices, intersecting adjacent segments, and setting Surface boundary conditions for matching segments.
To use the command, the following should be done:
```
python -m dragonfly edit solve-adjacency [PATH TO MODEL JSON]
```
> feat(cli): Add command to solve adjacency across a Model

- dragonfly/properties.py
- tests/json/model_with_nulls.json
- tests/model_test.py
As it was written, the re-serialization was working when there was no extension key (like 'energy') but, when 'energy' was set to None, it was failing. This fixes this issue.
> fix(from_dict): Ensure Model is re-serializable with null properties

- dragonfly/_base.py
- dragonfly/building.py
- dragonfly/context.py
- dragonfly/model.py
- dragonfly/properties.py
- dragonfly/room2d.py
- dragonfly/story.py
- dragonfly/windowparameter.py
- tests/building_test.py
- tests/context_test.py
- tests/json/model_with_nulls.json
- tests/json/sample_revit_model.json
- tests/model_test.py
- tests/room2d_test.py
- tests/shadingparameter_test.py
- tests/story_test.py
- tests/windowparameter_test.py
It took the whole day to get this together but honeybee_energy now uses "identifier" instead of "name".
This PR also adds a `user_data` key to all of the core objects.
The tests on this commit won't pass until the honeybee-core PR is merged in.
This PR should NOT be merged in until comparable PRs can be put together for the other 12 repos that are broken by this change.
> refactor(identifier): Change name property to identifier

- dragonfly/model.py
- requirements.txt
- tests/model_test.py
- tests/room2d_test.py
After some discussions with @mostaphaRoudsari , we have decided that the north should not be a property of the Model for the same reason why we don't have the location as a part of the model. The north direction is a property of the simulation assets like the skies used in Radiance or the simulation parameters used in our EnergyPlus.
> fix(model): Remove north from Model properties

- dragonfly/building.py
- dragonfly/room2d.py
- dragonfly/story.py
- requirements.txt
- tests/room2d_test.py
- tests/story_test.py
This commit fixes a previous issue where the assignment of interior apertures was raising an error upon translation to honeybee. I finally just made the decision that adjacency-setting should be done on the level of the story's translation to honeybee rather than the Room2D's translation. This way, we can make sure that adjacent interior apertures are always set correctly. I imagine this will also help manage walls with an AirBoundary type as well.
I also added a small method that handles the case where adjacent segments have matching WindowParameters but offset floor/ceiling heights. This new method means that interior apertures are valid even in these offset cases. So, as long as the WindowParamters match between adjacent segments, all will be good.
> fix(to_honeybee): Fix serialization of interior apertures to_honeybee

- dragonfly/room2d.py
- dragonfly/story.py
- tests/story_test.py
This commit fixes a bug that affects the case where Room2D floor_geometry vertices are not counter-clockwise in a JSON and they have Surface boundary conditions that reference other Room segments. Dragonfly automatically ensures that Room2D vertices are counterclockwise when it initializes the Room2D but this creates issues in the case of Surface boundary conditions since the adjacent segment is referenced by index and this index changes when the vertices are reversed.
So now we have a check that runs after Story serialization from_dict. This check determines if any Room2Ds have had their vertices reversed. If any of them have been reversed, it then looks through all of the boundary conditions and updates the Surface
boundary_condition_objects.
This will give me A LOT of peace of mind …
> fix(from_dict): Ensure correct reserilaization of adjacent BCs

- dragonfly/building.py
- dragonfly/context.py
- dragonfly/model.py
- dragonfly/room2d.py
- dragonfly/story.py
- dragonfly/writer/__init__.py
- dragonfly/writer/building.py
- dragonfly/writer/context.py
- dragonfly/writer/model.py
- dragonfly/writer/room2d.py
- dragonfly/writer/story.py
- tests/building_test.py
- tests/context_test.py
- tests/model_test.py
- tests/room2d_test.py
- tests/story_test.py
This commit adds writer modules to all objects (Model, Building, Story, Room2D, ContextShade). I have been able to get away without these methods up to this point since all workflows have used the to_honeybee or to_dict methods.  But I can see that some specific writer methods will be useful in export to URBANopt and in future UWG export workflows.  I might also use these to add some direct-to-idf methods at some point.
> feat(writer): Add writer modules to all model objects

- dragonfly/model.py
Now that the creation of this key is completely taken care of on the dragonfly-energy side of things, it's better to just not include it at all dragonfly-core, thereby avoiding potential mis-matches between this key and things happening with honeybee-energy.
> style(model): Remove detailed_model_filename

- dragonfly/extensionutil.py
This way, users don't have to specify properties for individual geometry objects if they are ok with the default.
Resolves https://github.com/ladybug-tools/dragonfly-core/issues/113
> fix(extensionutil): Handle the case of missing extension keys

- dragonfly/building.py
- requirements.txt
- tests/building_test.py
- tests/model_test.py
This commit adds an input argument for core/perimeter offset to the two classmethods that can be used to create Buildings from footprint
Current known limitations:
1) Any geometry with a hole is currently ignored and will just result in a single Room2D for the story.
2) The vast majority of geometries I tried from Rhino worked well but one particularly spiky one resulted in Rhino completely crashing. So I plan to turn it into a test such that @saeranv can hopefully catch this exception and avoid Rhino crashing.
Resolves https://github.com/ladybug-tools/dragonfly-core/issues/19
> feat(building): Add perimeter_offset as an option on classmethods

- requirements.txt
It looks like I accidentally reverted this in my second-to-last commit.
> fix(deps): bump honeybee-core from 1.32.0 to 1.32.1

- dragonfly/building.py
Now that saeran updated the exceptions raised for unsupported cases, I am changing the try/except loop to catch RuntimeErrors.
> style(polyskel): Only bypass polyskel for RuntimeError

- tests/room2d_test.py
@chriswmackey 
I checked my unit tests to see why my floor & ceiling plenum height check didn't fail with my previous incorrect code. However, it looks like my tests were written correctly (it's passing your changes correctly, and failing when I tested out my old way of calculating plenum height), so I can't figure out what exactly happened. Possibly some other changes managed to cancel out two wrongs. 
At any rate this PR just has some minor changes to my tests to get rid of the filtering I was doing to get rid of the None objects. It doesn't have any effect on the pass/fail status of the test, but just removes a redundancy.
> test(to_honeybee_plenum): Removing None filtering from tests.

- dragonfly/_base.py
- dragonfly/model.py
I originally had the property as read only in order to prevent the many cases where setting the identifier will break existing references across objects. But I think I have just come to realize that I can't stop people from playing with fire if they want to.  I guess people should be aware that re-setting a unique ID can have unintended consequences unless they know that they are doing.
> fix(identifier): Allow identifier to be set by the user

- README.md
- docs/index.rst
- dragonfly/cli/__init__.py
- dragonfly/cli/edit.py
- dragonfly/cli/translate.py
- dragonfly/cli/validate.py
- requirements.txt
- setup.py
The click dependency is now specified all of the way down in ladybug-core. And we're changing dragonfly-schema to always be installed whenever someone is using Python 3.6 or above.
> fix(deps): Remove [cli] option in favor of making it a requirement

- dragonfly/building.py
- dragonfly/cli/translate.py
- dragonfly/model.py
- dragonfly/story.py
The new option allows invalid Surface boundary conditions to be replaced with Outdoor ones upon translation to honeybee instead of raising an exception.
> fix(story): Add option to bypass invalid adjacency in to_honeybee

- dragonfly/cli/edit.py
- dragonfly/room2d.py
- dragonfly/story.py
- tests/cli_test.py
It can now control floor heights and takes default properties from the largest of the Room2Ds in each Polygon2D.
> fix(room2d): Improve the reset-room-boundaries command

- dragonfly/_base.py
- dragonfly/building.py
- dragonfly/room2d.py
- dragonfly/story.py
This was causing some bugs in cases where we try to generate something unique form the display_name. Like Sensor Grids here:
https://discourse.ladybug.tools/t/dragonfly-creating-duplicate-room-ids-that-mess-up-daylight-sensor-grids/22703/2
> fix(base): Get default state of display_name to last through duplication

- dragonfly/skylightparameter.py
- tests/model_test.py
This ensure that, when there are two roof polygons above a Room2D, they only get added to one of them.
> fix(skylight): Fix bug in previous commit

- dragonfly/room2d.py
- tests/room2d_test.py
This should address the case of "infinite" lines failing in the Model Editor.
> fix(room2d): Ensure Room2D.split_with_line handles extreme coordinates

- dragonfly/room2d.py
Namely, this happens when the Room2D segments are aligned to something within the Room2D boundary, causing vertices to fly off in a far away direction.
> fix(room2d): Catch cases where constrain_edges is undesirable

- dragonfly/roof.py
- tests/model_test.py
This commit includes several improvements that come courtesy of lots of real-world models. At this point, even the messiest Revit roofs that I have found can all be resolved into something that does not have any overlaps, meaning that they should always produce solid room volumes that account for the roof.
> fix(roof): Improve roof resolution to always remove overlaps

- dragonfly/roof.py
- dragonfly/room2d.py
- dragonfly/story.py
- tests/projection_test.py
- tests/roof_test.py
- tests/story_test.py
These will be used in the model editor to give users a level of control over how air boundaries are assigned.
> fix(room2d): Add methods to assign air boundaries to adjacencies

- dragonfly/room2d.py
This was a bug that happened when a wall segment was shared by two roof geometries and was perfectly co-aligned with both roof edges such that the end points of the wall segment fell completely within both roof edges.
> fix(room2d): Fix edge case bug in dragonfly room roof calculation
